### ISSUE TITLE
Collision accuracy problem

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/FreeIntv#18]
**Which version of RetroArch are you using?** 

- retroarch 1.7.1
- FreeIntv 1.0

**What system hardware are you using?**

- Nintendo New 3DS (11.6)  
- mac OS (10.13.4)

**What did you do?**

- Playing... Chip Shot: Super Pro Golf  
- Hit ball near shoreline

**What did you expect to happen?**

-  Ball should only splash when it comes into contact with the water

**What happened instead?**

- Collision happens at the wrong position (on land/sand)

## Notes
- This collision problem affects _at least_ water and trees on this game. Maybe even more game objects.
- Collision with when putting on green (zoomed view) is not affected

## Thoughts
- drawing offset?
- off-by-one issue?
- rounding error?
- precision?

## Screenshot 
Taken from video below. Dot in centre of "splash" is at the location of the ball. 
![screen shot 2018-04-10 at 12 18 45](https://user-images.githubusercontent.com/49612/38554330-1c47a070-3cba-11e8-935f-a1f807e0d2ed.png)

## Videos
- libretro-FreeIntv https://youtu.be/Yp-6bWEd_sE (ball splashes when on land)
- OpenEmu-Bliss  https://youtu.be/OB4FCmcD63U (ball can reach edge-most pixel of land)

**Comment by gingerbeardman** [comment]
Can you please give me some insight or reference as to the collision method? I'd like to take a look at this issue.

Cheers!

**Comment by recompileorg** [comment]
Everything I did is based on:
http://spatula-city.org/~im14u2c/intv/jzintv-1.0-beta3/doc/programming/stic.txt

All the collision stuff happens when the display is being drawn.  The code for both is mixed together in stic.c  

Collisions are pixel-perfect, so I have a buffer the same size as the display.  When I draw a pixel, a bit is added corresponding to what sprite (or border or background) the pixel belongs to.  Whatever is in the collision buffer at that point is ANDed to the sprite's collision register.  Non-interacting sprites are considered.

The code quality in that file is pretty low.  It's not the easiest file to understand and modify.  Sorry about that.

**Comment by gingerbeardman** [comment]
Hmm, given the limit of 8 Movable Objects (MOBs) I am now wondering if this is a collision problem at all? Is there a way of showing on screen what is and is not a MOB?

**Comment by recompileorg** [comment]
It should be easy enough to draw, say, a red box around MOBs if you want to easily identify them.

MOBs can collide with the border and parts of the background as well.  I didn't do much testing on that.  It's worth a look.

**Comment by gingerbeardman** [comment]
Yes, I'll have a poke around soon. 

I'm surprised it's not been noticed by anybody else in any other games.

**Comment by gingerbeardman** [comment]
OK, so I found a test cartridge called `MOB Collision Test.bin` which lets you test collision between MOB/background/border.

This shows some interesting results, but basically _FreeIntv_ seems have interrupted collision rather than the solid collision shown in _jzIntv_. This can be seen by the black/white flashing `[Bkg]` label when it should be constantly lit up white.

**Videos**
FreeIntv
https://youtu.be/2TCQ6CLsA9E

jzIntv
https://youtu.be/bP1CtPxwxaI

**Comment by gingerbeardman** [comment]
_Space Patrol Teaser Edition_ also suffers from this problem.

http://www.intellivision.us/roms/roms.php

**Comment by gingerbeardman** [comment]
Interestingly, running the MOB collision tear cart, the flashing when moving up or left is twice as fast moving down or right. 

Video: http://www.youtube.com/watch?v=iTqZ9R0dkyQ

**Comment by gingerbeardman** [comment]
_Joe’s MOB Test_ cart also shows the "interrupted" or "flashing" collision issue.

**Comment by gingerbeardman** [comment]
In _Stonix_ the ball collides randomly, regardless of it being near any bricks

**Comment by gingerbeardman** [comment]
@recompileorg do you have any time to look into this? At least to reproduce my tests?

**Comment by recompileorg** [comment]
@gingerbeardman  Yes, I was able to reproduce the issue with the test cart.  I don't have the other roms you tried, but I'll take your word for it.

The trouble is that I don't yet know why it's happening or how to fix it.   Really, that whole file needs to be rewritten.  I'll try to set aside some time this weekend to poke at it.  

This project really needs more developers.

**Comment by gingerbeardman** [comment]
I'm away for a few days but when I get back I'll be happy to continue down your path on this. How about starting a new branch for these changes? Then we can merge when "we" are happy with the fixed version?

**Comment by recompileorg** [comment]
@gingerbeardman

Good idea.  I've added a branch.  I'll await your return.

**Comment by gingerbeardman** [comment]
I'm back, I see what you mean about the hack... Hmm. Will look into things.

**Comment by gingerbeardman** [comment]
from: http://spatula-city.org/%7Eim14u2c/intv/jzintv-1.0-beta3/doc/programming/stic.txt
> All 10 collision bits are "sticky", meaning that once set by an interaction, they remain set until the CPU clears them. They will remain set even if the INTR bit is subsequently cleared. The CPU may also artificially set collision bits by writing to the collision registers, although bit #N for MOB #N will never read as 1 even if the CPU tries to set it. Also, writing a new value in bit #X for MOB #Y will not automatically change the value for bit #Y for MOB #X.

What do you think?

**Comment by recompileorg** [comment]
@gingerbeardman  That's the way it works without the hack, though self-collisions are "prevented" by  clearing them on every frame.  That's an easy fix, but not the cause of the issue.

The problem seems to be that the games aren't in-sync with the display.  That is, the display is being drawn (and collision bits set) when the game isn't expecting that to happen.   Game, then, occasionally  clear those bits and read them before the next frame is drawn.  The hack "works" by clearing those bits before the frame is drawn as many games aren't checking for collisions after they've cleared them. 
 
A possible fix that could hide the real issue is to manage the restrictions on when the cpu and stic are allowed to write.  That won't help with the timing issue though.

Frames are drawn every 14934 cycles, which isn't right as the number of cycles per frame can vary.  This could account for the speed issues as well.   All of that stuff can be found in intv.c in the exec function.

**Comment by gingerbeardman** [comment]
I'll the a further look, thanks for the summary

**Comment by recompileorg** [comment]
@gingerbeardman  It was a timing issue.  The MOB test cart works perfectly now.  You can also pick things up in AD&D.

**Comment by markwkidd** [comment]
Nice!!

**Comment by gingerbeardman** [comment]
Never have I used the 🎉 emoji with more meaning. Congrats on finding and solving the issue. 

(I'd resorted to playing on Wii/N3DS, which seemed - no real proof, just feeling - to have the issue less than SNES Mini)

Thanks again! Version bump?

**Comment by recompileorg** [comment]
Thanks.  I don't know that it's ready for a version bump quite yet.  I'd like to redo quite a bit of the STIC implementation first.  It was rushed and poorly written, making it difficult to track down problems.  I was working on a problem with 'Triple Action' today and found some pretty big issues that are probably best addressed with big rewrite.

**Comment by gingerbeardman** [comment]
No worries at all, you're the boss!

I'm also intrigued if any of the other issues I raised, especially the pull shooting on direction 
https://github.com/libretro/FreeIntv/issues/27, are solved with the timing fix?
